name: staff_verify
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1


#------------------------- PACKAGES DEPENDENCIES --------------------------------#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3
  loading_animation_widget: ^1.3.0
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_barcode_scanner: 2.0.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  qr_flutter: ^4.1.0
  cloudinary_dart: ^0.0.11
  cloudinary_api: ^1.1.0
  cloudinary_public: ^0.23.1
  path_provider: ^2.1.5
  random_string: ^2.3.1
  file_saver: ^0.2.14
  pdf: ^3.11.3
  printing: ^5.14.2

#  cloudinary_dart: ^1.0.0
#  cloudinary_api: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

#---------------ASSETS------------------------#
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/



#----------------------------FONTS-------------------------#
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
